variables: 
  outputfolder: $CI_PROJECT_DIR/AIR_2.00/target/
  buildfolder: AIR_2.00

#######################################
# WEBA Infos 
  REMOTE_REPO: by-gitlab.de.bayer.cnb/lamp/air.git
  PROJECT_TOKEN_NAME: air
  TOKEN: 6jyTZLFVw3oPPPs8wwSM 
  REPO_BRANCH: master
#######################################

include:
  - project: 'shared/templates'
    file: '/gitlab-ci.yml.templates/.shared-dind-buildsync.yml'
    
stages:
  - build
  - push

build:
  extends: .maven_build
  only:
    - Docker_Test  
  stage: build  
  
push:
  extends: .push_to_weba
  only:
    - Docker_Test  
  stage: push    